services:
  postgres_db:
    image: postgres:16-alpine 
    container_name: my_postgres_db
    
    env_file: # !!! Load environment variables from .env file
      - .env
      
    volumes:
      - postgres_data:/var/lib/postgresql
      
    ports:
      - "5433:5432" # avoid conflict with local Postgres
      
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local